#!/usr/bin/env bash

db_params() {
    echo "dbname=$1 user=$2 sslrootcert=rds-combined-ca-bundle.pem sslmode=verify-ca"
}

if [ "$MODE" == "bootstrap" ] ; then

    export PGPASSWORD=${ROOT_DB_PASSWORD}


    psql -h${PTTG_DB_HOSTNAME} "$(db_params postgres root)" -tc "SELECT 1 FROM pg_database WHERE datname = '${HMRC_AC_DB_NAME}'" | grep -q 1 || psql -h${PTTG_DB_HOSTNAME} "$(db_params postgres root)" -c "CREATE DATABASE ${HMRC_AC_DB_NAME}"

    psql -h${PTTG_DB_HOSTNAME} "$(db_params ${HMRC_AC_DB_NAME} root)" << EOFA

        CREATE SCHEMA IF NOT EXISTS ${HMRC_AC_DB_SCHEMA_NAME};

        CREATE USER ${HMRC_AC_DB_USERNAME} WITH PASSWORD '${HMRC_AC_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON SCHEMA ${HMRC_AC_DB_SCHEMA_NAME} TO ${HMRC_AC_DB_USERNAME};
EOFA



    psql -h${PTTG_DB_HOSTNAME} "$(db_params postgres root)" -tc "SELECT 1 FROM pg_database WHERE datname = '${PTTG_DB_NAME}'" | grep -q 1 || psql -h${PTTG_DB_HOSTNAME} "$(db_params postgres root)" -c "CREATE DATABASE ${PTTG_DB_NAME}"

    psql -h${PTTG_DB_HOSTNAME} "$(db_params ${PTTG_DB_NAME} root)" << EOFB

        CREATE SCHEMA IF NOT EXISTS ${IP_SCHEMA_NAME};

        CREATE USER ${IP_DB_USERNAME} WITH PASSWORD '${IP_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_USERNAME};

        CREATE USER ${IP_DB_QUERY_USERNAME} WITH PASSWORD '${IP_DB_QUERY_PASSWORD}';
        GRANT USAGE ON SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};
EOFB


    export PGPASSWORD=${IP_DB_PASSWORD}


    psql -h${PTTG_DB_HOSTNAME} "$(db_params ${PTTG_DB_NAME} ${IP_DB_USERNAME})" << EOFC

        GRANT SELECT ON ALL TABLES IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};
        GRANT SELECT ON ALL SEQUENCES IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};
        GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};

        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT SELECT ON TABLES TO ${IP_DB_QUERY_USERNAME};
        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT SELECT ON SEQUENCES TO ${IP_DB_QUERY_USERNAME};
        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT EXECUTE ON FUNCTIONS TO ${IP_DB_QUERY_USERNAME};
EOFC

else
    tail -f /dev/null
fi
