#!/usr/bin/env bash

if [ "$MODE" == "bootstrap" ] ; then

    export PGPASSWORD=${ROOT_DB_PASSWORD}

    psql -h${PTTG_DB_HOSTNAME} -Uroot -dpostgres -tc "SELECT 1 FROM pg_database WHERE datname = '${HMRC_AC_DB_NAME}'" | grep -q 1 || psql -h${PTTG_DB_HOSTNAME} -Uroot -dpostgres -c "CREATE DATABASE ${HMRC_AC_DB_NAME}"

    echo 'After creation of HMRC db'

    psql -h${PTTG_DB_HOSTNAME} -Uroot -d${PTTG_DB_NAME} << EOFA

        CREATE SCHEMA IF NOT EXISTS ${IP_SCHEMA_NAME};
        CREATE USER ${IP_DB_USERNAME} WITH PASSWORD '${IP_DB_PASSWORD}';

        GRANT ALL PRIVILEGES ON SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_USERNAME};

        CREATE USER ${IP_DB_QUERY_USERNAME} WITH PASSWORD '${IP_DB_QUERY_PASSWORD}';

EOFA

    echo 'before hmrc schema creation'
    echo ${HMRC_AC_DB_NAME}
    echo ${HMRC_AC_DB_SCHEMA_NAME}
    echo ${HMRC_AC_DB_USERNAME}
    echo ${HMRC_AC_DB_PASSWORD}

    psql -h${PTTG_DB_HOSTNAME} -Uroot -d${HMRC_AC_DB_NAME} << EOFB

        CREATE SCHEMA IF NOT EXISTS ${HMRC_AC_DB_SCHEMA_NAME};
        CREATE USER ${HMRC_AC_DB_USERNAME} WITH PASSWORD '${HMRC_AC_DB_PASSWORD}';

        GRANT ALL PRIVILEGES ON SCHEMA ${HMRC_AC_DB_SCHEMA_NAME} TO ${HMRC_AC_DB_USERNAME};

EOFB
    echo 'after hmrc schema creation'

    export PGPASSWORD=${IP_DB_PASSWORD}

    psql -h${PTTG_DB_HOSTNAME} -U${IP_DB_USERNAME} -d${PTTG_DB_NAME} << EOFC

        GRANT SELECT ON ALL TABLES IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};
        GRANT SELECT ON ALL SEQUENCES IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};
        GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${IP_SCHEMA_NAME} TO ${IP_DB_QUERY_USERNAME};

        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT SELECT ON TABLES TO ${IP_DB_QUERY_USERNAME};
        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT SELECT ON SEQUENCES TO ${IP_DB_QUERY_USERNAME};
        ALTER DEFAULT PRIVILEGES IN SCHEMA ${IP_SCHEMA_NAME} GRANT EXECUTE ON FUNCTIONS TO ${IP_DB_QUERY_USERNAME};
EOFC

else
    tail -f /dev/null
fi
